[package]
name = "benchmarks"
version = "0.1.0"
edition = "2024"

[dependencies]
revm.workspace = true
anyhow.workspace = true




[dev-dependencies]
criterion = "0.5.1"


[[bench]]
name = "erc20_evm"
harness = false
